services:
  - type: web
    name: alina-mega-sales-bot2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    runtime: python-3.10.13
